# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html

security:
    
    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username
                # if you're using multiple entity managers
                # manager_name: customer

    firewalls:
    
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            anonymous: ~
            provider: our_db_provider
            form_login:
                login_path: login
                check_path: login
                default_target_path: /home
        
            logout:
                path:   /logout
                target: /
                
                
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost:      15
            
            
    access_control:
        # require ROLE_USER for /home*
        - { path: ^/home, roles: ROLE_USER }
